/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.daijobudes.psaform.adminGUI;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.table.DefaultTableModel;

import io.github.daijobudes.psaform.SQLConnect;

/**
 *
 * @author DaijobuDes
 */
public class AdminDisplayForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminDisplayForm
     */

    SQLConnect dbcon = new SQLConnect();
    public AdminDisplayForm() {
        initComponents();
        try {
            dbcon.connectDB();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(AdminDisplayForm.class.getName()).log(java.util.logging.Level.SEVERE, "Error: {0} with stacktrace {1}", new Object[]{ex.getMessage(), ex.getStackTrace()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableDisplay = new javax.swing.JTable();
        clearTableBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        menuBtn = new javax.swing.JButton();
        displayAllBtn = new javax.swing.JButton();
        lastnameSearch = new javax.swing.JButton();
        lastnameText = new javax.swing.JTextField();
        firstnameSearch = new javax.swing.JButton();
        firstnameText = new javax.swing.JTextField();
        middlenameSearch = new javax.swing.JButton();
        middlenameText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Last Name", "First Name", "Middle Name", "Month", "Day", "Year", "Place of Birth", "Country", "Father's Last Name", "Father's First Name", "Father's Middle Name", "Mother's Last Name", "Mother's First Name", "Mother's Middle Name"
            }
        ));
        tableDisplay.setEnabled(false);
        jScrollPane1.setViewportView(tableDisplay);

        clearTableBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearTableBtn.setText("Clear Table");
        clearTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTableBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Record Display Section");

        menuBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuBtn.setText("Back To Menu");
        menuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBtnActionPerformed(evt);
            }
        });

        displayAllBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        displayAllBtn.setText("Display All");
        displayAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayAllBtnActionPerformed(evt);
            }
        });

        lastnameSearch.setText("Last Name Search");
        lastnameSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameSearchActionPerformed(evt);
            }
        });

        lastnameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameTextActionPerformed(evt);
            }
        });

        firstnameSearch.setText("First Name Search");
        firstnameSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameSearchActionPerformed(evt);
            }
        });

        firstnameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameTextActionPerformed(evt);
            }
        });

        middlenameSearch.setText("Middle Name Search");
        middlenameSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middlenameSearchActionPerformed(evt);
            }
        });

        middlenameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middlenameTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1158, Short.MAX_VALUE)
                        .addContainerGap(44, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(middlenameSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(firstnameSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lastnameSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(middlenameText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 615, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(menuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clearTableBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(displayAllBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(205, 205, 205))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameSearch)
                    .addComponent(lastnameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayAllBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnameSearch)
                    .addComponent(firstnameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearTableBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(middlenameSearch)
                    .addComponent(middlenameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuBtn))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTableBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tableDisplay.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_clearTableBtnActionPerformed

    private void menuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBtnActionPerformed
        // TODO add your handling code here:
        AdminMenu am = new AdminMenu();
        am.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuBtnActionPerformed

    private void displayAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayAllBtnActionPerformed
        try {
            // TODO add your handling code here:
            ResultSet rs = dbcon.displayRecords();

            while (tableDisplay.getRowCount() > 0) {
                ((DefaultTableModel)tableDisplay.getModel()).removeRow(0);
            }

            int col = rs.getMetaData().getColumnCount();

            while (rs.next()) {
                Object[] row = new Object[col];

                for (int i = 1; i <= col; i++) {
                    row[i-1] = rs.getObject(i);
                }
                ((DefaultTableModel)tableDisplay.getModel()).insertRow(rs.getRow()-1, row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminDisplayForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_displayAllBtnActionPerformed

    private void lastnameSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameSearchActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs = dbcon.displaySearch("LASTNAME", lastnameText.getText());

            while (tableDisplay.getRowCount() > 0) {
                ((DefaultTableModel)tableDisplay.getModel()).removeRow(0);
            }

            int col = rs.getMetaData().getColumnCount();

            while (rs.next()) {
                Object[] row = new Object[col];

                for (int i = 1; i <= col; i++) {
                    row[i-1] = rs.getObject(i);
                }
                ((DefaultTableModel)tableDisplay.getModel()).insertRow(rs.getRow()-1, row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminDisplayForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(AdminDisplayForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lastnameSearchActionPerformed

    private void lastnameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameTextActionPerformed

    private void firstnameSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameSearchActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs = dbcon.displaySearch("FIRSTNAME", firstnameText.getText());

            while (tableDisplay.getRowCount() > 0) {
                ((DefaultTableModel)tableDisplay.getModel()).removeRow(0);
            }

            int col = rs.getMetaData().getColumnCount();

            while (rs.next()) {
                Object[] row = new Object[col];

                for (int i = 1; i <= col; i++) {
                    row[i-1] = rs.getObject(i);
                }
                ((DefaultTableModel)tableDisplay.getModel()).insertRow(rs.getRow()-1, row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminDisplayForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(AdminDisplayForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_firstnameSearchActionPerformed

    private void firstnameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameTextActionPerformed

    private void middlenameSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middlenameSearchActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs = dbcon.displaySearch("MIDDLENAME", middlenameText.getText());

            while (tableDisplay.getRowCount() > 0) {
                ((DefaultTableModel)tableDisplay.getModel()).removeRow(0);
            }

            int col = rs.getMetaData().getColumnCount();

            while (rs.next()) {
                Object[] row = new Object[col];

                for (int i = 1; i <= col; i++) {
                    row[i-1] = rs.getObject(i);
                }
                ((DefaultTableModel)tableDisplay.getModel()).insertRow(rs.getRow()-1, row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminDisplayForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(AdminDisplayForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_middlenameSearchActionPerformed

    private void middlenameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middlenameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middlenameTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDisplayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDisplayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDisplayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDisplayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDisplayForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearTableBtn;
    private javax.swing.JButton displayAllBtn;
    private javax.swing.JButton firstnameSearch;
    private javax.swing.JTextField firstnameText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lastnameSearch;
    private javax.swing.JTextField lastnameText;
    private javax.swing.JButton menuBtn;
    private javax.swing.JButton middlenameSearch;
    private javax.swing.JTextField middlenameText;
    private javax.swing.JTable tableDisplay;
    // End of variables declaration//GEN-END:variables
}
