CREATE TABLE USERFORM (
    TABLEID INTEGER,
    LASTNAME VARCHAR(64),
    FIRSTNAME VARCHAR(64),
    MIDDLENAME VARCHAR(64),
    DATEM INTEGER,
    DATED INTEGER,
    DATEY INTEGER,
    PLACEOFBIRTH VARCHAR(256),
    COUNTRY VARCHAR(32),
    LASTNAMEFATHER VARCHAR(64),
    FIRSTNAMEFATHER VARCHAR(64),
    MIDDLENAMEFATHER VARCHAR(64),
    LASTNAMEMOTHER VARCHAR(64),
    FIRSTNAMEMOTHER VARCHAR(64),
    MIDDLENAMEMOTHER VARCHAR(64)
);

INSERT INTO JAVA.USERFORM (TABLEID, LASTNAME, FIRSTNAME, MIDDLENAME, DATEM, DATED, DATEY, PLACEOFBIRTH, COUNTRY, LASTNAMEFATHER, FIRSTNAMEFATHER, MIDDLENAMEFATHER, LASTNAMEMOTHER, FIRSTNAMEMOTHER, MIDDLENAMEMOTHER) 
	VALUES (1, 'CELLAN', 'KATE AUBREY', 'ROSANO', 8, 19, 2000, 'CEBU CITY', 'PHILIPPINES', 'DFDSHKSFHJSDK', 'OIUWEEOIRUW', 'SJFHSDKJFH', 'OIWEUROWEIU', 'KJHDSKDJ', 'FLSKJFSDF');
INSERT INTO JAVA.USERFORM (TABLEID, LASTNAME, FIRSTNAME, MIDDLENAME, DATEM, DATED, DATEY, PLACEOFBIRTH, COUNTRY, LASTNAMEFATHER, FIRSTNAMEFATHER, MIDDLENAMEFATHER, LASTNAMEMOTHER, FIRSTNAMEMOTHER, MIDDLENAMEMOTHER) 
	VALUES (2, 'ICHINOSE', 'MAINE', 'SYLVIA', 1, 23, 1998, 'CEBU CITY', 'JAPAN', 'ASJHDFSKJH', 'OWIWUEROIWU', 'XCMNBXV', 'SDFLKJS', 'WEIOURWO', 'SLKJSDFLKJ');
INSERT INTO JAVA.USERFORM (TABLEID, LASTNAME, FIRSTNAME, MIDDLENAME, DATEM, DATED, DATEY, PLACEOFBIRTH, COUNTRY, LASTNAMEFATHER, FIRSTNAMEFATHER, MIDDLENAMEFATHER, LASTNAMEMOTHER, FIRSTNAMEMOTHER, MIDDLENAMEMOTHER) 
	VALUES (3, 'LASTNAME', 'FIRSTNAME', 'MIDDLENAME', 1, 2, 1999, 'CEBU CITY', 'PHILIPPINES', 'LASTNAMENIPAPA', 'PANGALANNIPAPA', 'MIDDLENAMENIPAPA', 'LASTNAMENIMAMA', 'PANGALANNIMAMA', 'MIDDLENAMENIMAMA');
INSERT INTO JAVA.USERFORM (TABLEID, LASTNAME, FIRSTNAME, MIDDLENAME, DATEM, DATED, DATEY, PLACEOFBIRTH, COUNTRY, LASTNAMEFATHER, FIRSTNAMEFATHER, MIDDLENAMEFATHER, LASTNAMEMOTHER, FIRSTNAMEMOTHER, MIDDLENAMEMOTHER) 
	VALUES (4, 'MANGANESE', 'MANGA', 'MANGO', 6, 7, 2003, 'MANGO AVENUE CEBU CITY', 'PHILIPPINES', 'MANGANESE', 'MAGNESIUM', 'MAGNA', 'MANGA', 'MAGNUM', 'MAAGA');
INSERT INTO JAVA.USERFORM (TABLEID, LASTNAME, FIRSTNAME, MIDDLENAME, DATEM, DATED, DATEY, PLACEOFBIRTH, COUNTRY, LASTNAMEFATHER, FIRSTNAMEFATHER, MIDDLENAMEFATHER, LASTNAMEMOTHER, FIRSTNAMEMOTHER, MIDDLENAMEMOTHER) 
	VALUES (5, 'POGI', 'MASTER', 'AWERS', 7, 28, 2001, 'CEBU CITY', 'PHILIPPINES', 'GWAPO', 'KAAYO', 'KO', 'GWAPA', 'BITAW', 'KA');
INSERT INTO JAVA.USERFORM (TABLEID, LASTNAME, FIRSTNAME, MIDDLENAME, DATEM, DATED, DATEY, PLACEOFBIRTH, COUNTRY, LASTNAMEFATHER, FIRSTNAMEFATHER, MIDDLENAMEFATHER, LASTNAMEMOTHER, FIRSTNAMEMOTHER, MIDDLENAMEMOTHER) 
	VALUES (6, 'TEST', 'TEST', 'TEST', 1, 1, 1980, 'TEST CITY', 'TESTING', 'TEST', 'TEST', 'TEST', 'TEST', 'TEST', 'TEST');
INSERT INTO JAVA.USERFORM (TABLEID, LASTNAME, FIRSTNAME, MIDDLENAME, DATEM, DATED, DATEY, PLACEOFBIRTH, COUNTRY, LASTNAMEFATHER, FIRSTNAMEFATHER, MIDDLENAMEFATHER, LASTNAMEMOTHER, FIRSTNAMEMOTHER, MIDDLENAMEMOTHER) 
	VALUES (7, 'ANON', 'JOHN', 'DOE', 11, 4, 1995, 'CALIFORNIA CITY', 'UNITED STATES OF AMERICA', 'ANON', 'JOHNNY', 'DOE', 'THIS', 'MARY', 'DON');
